package dtos

const (
	WorkOrderInvoiceActiveState   = 1
	WorkOrderInvoiceInactiveState = 2
)

type WorkOrderInvoiceRequestDTO struct {
	Id                       string `json:"id"`
	Uuid                     string `json:"uuid"`
	TenantID                 string `json:"tenant_id"`
	OrderId                  string `json:"order_id"`
	InvoiceID                string `json:"invoice_id"`
	InvoiceDate              string `json:"invoice_date"`
	AssociateName            string `json:"associate_name"`
	AssociateTelephone       string `json:"associate_telephone"`
	ClientName               string `json:"client_name"`
	ClientTelephone          string `json:"client_telephone"`
	ClientEmail              string `json:"client_email"`
	Line01Qty                string `json:"line_01_qty"`
	Line01Desc               string `json:"line_01_desc"`
	Line01Price              string `json:"line_01_price"`
	Line01Amount             string `json:"line_01_amount"`
	Line02Qty                string `json:"line_02_qty"`
	Line02Desc               string `json:"line_02_desc"`
	Line02Price              string `json:"line_02_price"`
	Line02Amount             string `json:"line_02_amount"`
	Line03Qty                string `json:"line_03_qty"`
	Line03Desc               string `json:"line_03_desc"`
	Line03Price              string `json:"line_03_price"`
	Line03Amount             string `json:"line_03_amount"`
	Line04Qty                string `json:"line_04_qty"`
	Line04Desc               string `json:"line_04_desc"`
	Line04Price              string `json:"line_04_price"`
	Line04Amount             string `json:"line_04_amount"`
	Line05Qty                string `json:"line_05_qty"`
	Line05Desc               string `json:"line_05_desc"`
	Line05Price              string `json:"line_05_price"`
	Line05Amount             string `json:"line_05_amount"`
	Line06Qty                string `json:"line_06_qty"`
	Line06Desc               string `json:"line_06_desc"`
	Line06Price              string `json:"line_06_price"`
	Line06Amount             string `json:"line_06_amount"`
	Line07Qty                string `json:"line_07_qty"`
	Line07Desc               string `json:"line_07_desc"`
	Line07Price              string `json:"line_07_price"`
	Line07Amount             string `json:"line_07_amount"`
	Line08Qty                string `json:"line_08_qty"`
	Line08Desc               string `json:"line_08_desc"`
	Line08Price              string `json:"line_08_price"`
	Line08Amount             string `json:"line_08_amount"`
	Line09Qty                string `json:"line_09_qty"`
	Line09Desc               string `json:"line_09_desc"`
	Line09Price              string `json:"line_09_price"`
	Line09Amount             string `json:"line_09_amount"`
	Line10Qty                string `json:"line_10_qty"`
	Line10Desc               string `json:"line_10_desc"`
	Line10Price              string `json:"line_10_price"`
	Line10Amount             string `json:"line_10_amount"`
	Line11Qty                string `json:"line_11_qty"`
	Line11Desc               string `json:"line_11_desc"`
	Line11Price              string `json:"line_11_price"`
	Line11Amount             string `json:"line_11_amount"`
	Line12Qty                string `json:"line_12_qty"`
	Line12Desc               string `json:"line_12_desc"`
	Line12Price              string `json:"line_12_price"`
	Line12Amount             string `json:"line_12_amount"`
	Line13Qty                string `json:"line_13_qty"`
	Line13Desc               string `json:"line_13_desc"`
	Line13Price              string `json:"line_13_price"`
	Line13Amount             string `json:"line_13_amount"`
	Line14Qty                string `json:"line_14_qty"`
	Line14Desc               string `json:"line_14_desc"`
	Line14Price              string `json:"line_14_price"`
	Line14Amount             string `json:"line_14_amount"`
	Line15Qty                string `json:"line_15_qty"`
	Line15Desc               string `json:"line_15_desc"`
	Line15Price              string `json:"line_15_price"`
	Line15Amount             string `json:"line_15_amount"`
	InvoiceQuoteDays         string `json:"invoice_quote_days"`
	InvoiceAssociateTax      string `json:"invoice_associate_tax"`
	InvoiceQuoteDate         string `json:"invoice_quote_date"`
	InvoiceCustomersApproval string `json:"invoice_customers_approval"`
	Line01Notes              string `json:"line_01_notes"`
	Line02Notes              string `json:"line_02_notes"`
	TotalLabour              string `json:"total_labour"`
	TotalMaterials           string `json:"total_materials"`
	OtherCosts               string `json:"other_costs"`
	Tax                      string `json:"tax"`
	Total                    string `json:"total"`
	PaymentAmount            string `json:"payment_amount"`
	PaymentDate              string `json:"payment_date"`
	IsCash                   string `json:"is_cash"`
	IsCheque                 string `json:"is_cheque"`
	IsDebit                  string `json:"is_debit"`
	IsCredit                 string `json:"is_credit"`
	IsOther                  string `json:"is_other"`
	ClientSignature          string `json:"client_signature"`
	AssociateSignDate        string `json:"associate_sign_date"`
	AssociateSignature       string `json:"associate_signature"`
	WorkOrderId              string `json:"work_order_id"`
	CreatedTime              string `json:"created_time"`
	LastModifiedTime         string `json:"last_modified_time"`
	CreatedById              string `json:"created_by_id"`
	CreatedByName            string `json:"created_by_name"`
	LastModifiedById         string `json:"last_modified_by_id"`
	LastModifiedByName       string `json:"last_modified_by_name"`
	CreatedFrom              string `json:"created_from"`
	CreatedFromIsPublic      string `json:"created_from_is_public"`
	LastModifiedFrom         string `json:"last_modified_from"`
	LastModifiedFromIsPublic string `json:"last_modified_from_is_public"`
	ClientAddress            string `json:"client_address"`
	RevisionVersion          string `json:"revision_version"`
	Deposit                  string `json:"deposit"`
	AmountDue                string `json:"amount_due"`
	SubTotal                 string `json:"sub_total"`
	State                    string `json:"state"` // IsArchived string `json:"is_archived"`
	OldId                    string `json:"old_id"`
}
type WorkOrderInvoiceResponseDTO struct {
	FileName string `json:"file_name"`
	Content  []byte `json:"content"`
}
