# DOCKERFILE IS USED IF YOU WOULD LIKE TO SETUP A STAND ALONE CONTAINER FOR YOUR
# DEVELOPMENT NEEDS WHICH INCLUDES LOCAL STORAGE.
version: '3.9'
services:
  app:
    stdin_open: true
    container_name: workery-invoicebuilder
    image: over55/workery-invoicebuilder:1.0
    environment:
        WORKERY_INVOICEBUILDER_IP: 0.0.0.0
        WORKERY_INVOICEBUILDER_PORT: 8001
        WORKERY_INVOICEBUILDER_PDF_TEMPLATE_FILE_PATH: Template_Live_v2.pdf
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - data:/data

volumes:
    data:
