"""
Client demonstrates how to make a call to the server and save the PDF file
generated by the server to our local directory.
"""
from __future__ import print_function
import logging

import grpc

import invoice_pb2
import invoice_pb2_grpc


def save_chunks_to_file(chunks, filename):
    """
    Utility function will take the chunks recieved from the remote server
    and save the chunks to a local file. Special thanks to the following:
    https://github.com/gooooloo/grpc-file-transfer
    """
    with open(filename, 'wb') as f:
        for chunk in chunks:
            f.write(chunk.buffer)


def run():
    # NOTE(gRPC Python Team): .close() is possible on a channel and should be
    # used in circumstances in which the with statement does not fit the needs
    # of the code.
    with grpc.insecure_channel('localhost:50051') as channel:
        stub = invoice_pb2_grpc.InvoiceBuilderStub(channel)
        response = stub.GeneratePDF(invoice_pb2.GeneratePDFRequest(
            invoiceId='1',
            invoiceDate='2019-01-01',
            associateName='Bob the Builder11111111111',
            associateTelephone='(123) 456-7898',
            clientName = 'John Smith11111111111111111111111111111122222222222222222222222',
            clientAddress = '123-321 Simple Road, London, Ontario, Canada, N6J 4X4',
            clientTelephone = '(999) 999-9999',
            clientEmail = 'john@smith.com',
            line01Quantity = '1',
            line01Description = 'This is a somesort of description.12345678901',
            line01Price = '$100.00',
            line01Amount = '$100.00',
            line02Quantity = '',
            line02Description = '',
            line02Price = '',
            line02Amount = '',
            line03Quantity = '',
            line03Description = '',
            line03Price = '',
            line03Amount = '',
            line04Quantity = '',
            line04Description = '',
            line04Price = '',
            line04Amount = '',
            line05Quantity = '',
            line05Description = '',
            line05Price = '',
            line05Amount = '',
            line06Quantity = '',
            line06Description = '',
            line06Price = '',
            line06Amount = '',
            line07Quantity = '',
            line07Description = '',
            line07Price = '',
            line07Amount = '',
            line08Quantity = '',
            line08Description = '',
            line08Price = '',
            line08Amount = '',
            line09Quantity = '',
            line09Description = '',
            line09Price = '',
            line09Amount = '',
            line10Quantity = '',
            line10Description = '',
            line10Price = '',
            line10Amount = '',
            line11Quantity = '',
            line11Description = '',
            line11Price = '',
            line11Amount = '',
            line12Quantity = '',
            line12Description = '',
            line12Price = '',
            line12Amount = '',
            line13Quantity = '',
            line13Description = '',
            line13Price = '',
            line13Amount = '',
            line14Quantity = '',
            line14Description = '',
            line14Price = '',
            line14Amount = '',
            line15Quantity = '',
            line15Description = '',
            line15Price = '',
            line15Amount = '',
            invoiceQuoteDays = '15',
            invoiceAssociateTax = '1234567-R12311',
            invoiceQuoteDate = '2019-01-01',
            invoiceCustomersApproval = 'John Smith1111111111',
            line01Notes = 'This is somesort of text.1111111111111111111111111111111111111111111111111111111',
            line02Notes = '11111111111111111111111111111111111111111',
            totalLabour = '$100.00',
            totalMaterials = '$100.00',
            otherCosts = '',
            amountDue = '$100.00',
            tax = '$13.00',
            total = '$130.00',
            grandTotal = '$130.00',
            paymentAmount = '$130.00', # DEPRECATED
            paymentDate = '2019-01-01',
            cash = 'X',
            cheque = '',
            debit = '',
            credit = '',
            other = '',
            clientSignature = 'John Smith6666666666666666666666666666666666666',
            associateSignDate = '2019-01-01',
            associateSignature = 'Bob the Builder11111111111111',
            workOrderId = '1234567',
            subTotal = '$1,234.00',
        ))
        save_chunks_to_file(response, "bin/sample.pdf")


if __name__ == '__main__':
    logging.basicConfig()
    run()
