# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import invoice_pb2 as invoice__pb2


class InvoiceBuilderStub(object):
  """The invoice builder service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GeneratePDF = channel.unary_stream(
        '/InvoiceBuilder/GeneratePDF',
        request_serializer=invoice__pb2.GeneratePDFRequest.SerializeToString,
        response_deserializer=invoice__pb2.Chunk.FromString,
        )


class InvoiceBuilderServicer(object):
  """The invoice builder service definition.
  """

  def GeneratePDF(self, request, context):
    """Generate standard workery invoice templated PDF file.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_InvoiceBuilderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GeneratePDF': grpc.unary_stream_rpc_method_handler(
          servicer.GeneratePDF,
          request_deserializer=invoice__pb2.GeneratePDFRequest.FromString,
          response_serializer=invoice__pb2.Chunk.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'InvoiceBuilder', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
