site_name: Workery InvoiceBuilder
nav:
    - Home: index.md
    - Installation:
        - Quickinstall: installation/quickinstall.md
        - Production: installation/production.md
    - License: license.md
theme: readthedocs
