version: '3'

tasks:
  start:
    cmds:
      - docker-compose up -d

  stop:
    cmds:
      - docker-compose down

  console:
    cmds:
      - docker exec -it workery-invoicebuilder bash

  deploy:
    cmds:
      - docker build -f Dockerfile -t over55/workery-invoicebuilder:latest --platform linux/amd64 .
      - docker tag over55/workery-invoicebuilder:latest over55/workery-invoicebuilder:latest
      - docker push over55/workery-invoicebuilder:latest
